# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from sgtk.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1150, 643)
        Dialog.setStyleSheet("")
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setContentsMargins(20, 10, 20, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbar_widget = QtGui.QWidget(Dialog)
        self.toolbar_widget.setObjectName("toolbar_widget")
        self.header_layout = QtGui.QHBoxLayout(self.toolbar_widget)
        self.header_layout.setContentsMargins(0, 0, 0, 5)
        self.header_layout.setObjectName("header_layout")
        self.toolbar_hlayout = QtGui.QHBoxLayout()
        self.toolbar_hlayout.setSpacing(15)
        self.toolbar_hlayout.setContentsMargins(0, 0, 0, 0)
        self.toolbar_hlayout.setObjectName("toolbar_hlayout")
        self.refresh_btn = QtGui.QToolButton(self.toolbar_widget)
        self.refresh_btn.setText("")
        self.refresh_btn.setObjectName("refresh_btn")
        self.toolbar_hlayout.addWidget(self.refresh_btn)
        self.group_by_hlayout = QtGui.QHBoxLayout()
        self.group_by_hlayout.setSpacing(5)
        self.group_by_hlayout.setObjectName("group_by_hlayout")
        self.group_by_label = QtGui.QLabel(self.toolbar_widget)
        self.group_by_label.setObjectName("group_by_label")
        self.group_by_hlayout.addWidget(self.group_by_label)
        self.group_by_combo_box = QtGui.QComboBox(self.toolbar_widget)
        self.group_by_combo_box.setObjectName("group_by_combo_box")
        self.group_by_hlayout.addWidget(self.group_by_combo_box)
        self.toolbar_hlayout.addLayout(self.group_by_hlayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.toolbar_hlayout.addItem(spacerItem)
        self.view_mode_hlayout = QtGui.QHBoxLayout()
        self.view_mode_hlayout.setSpacing(5)
        self.view_mode_hlayout.setObjectName("view_mode_hlayout")
        self.thumbnail_view_btn = QtGui.QToolButton(self.toolbar_widget)
        self.thumbnail_view_btn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.thumbnail_view_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tk-multi-breakdown2/icons/mode_switch_thumb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/tk-multi-breakdown2/icons/mode_switch_thumb_active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.thumbnail_view_btn.setIcon(icon)
        self.thumbnail_view_btn.setCheckable(True)
        self.thumbnail_view_btn.setChecked(False)
        self.thumbnail_view_btn.setAutoRaise(False)
        self.thumbnail_view_btn.setObjectName("thumbnail_view_btn")
        self.view_mode_hlayout.addWidget(self.thumbnail_view_btn)
        self.list_view_btn = QtGui.QToolButton(self.toolbar_widget)
        self.list_view_btn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.list_view_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/tk-multi-breakdown2/icons/mode_switch_card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/tk-multi-breakdown2/icons/mode_switch_card_active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.list_view_btn.setIcon(icon1)
        self.list_view_btn.setCheckable(True)
        self.list_view_btn.setAutoRaise(False)
        self.list_view_btn.setObjectName("list_view_btn")
        self.view_mode_hlayout.addWidget(self.list_view_btn)
        self.grid_view_btn = QtGui.QToolButton(self.toolbar_widget)
        self.grid_view_btn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.grid_view_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/tk-multi-breakdown2/icons/grid-inactive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/tk-multi-breakdown2/icons/grid-active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.grid_view_btn.setIcon(icon2)
        self.grid_view_btn.setCheckable(True)
        self.grid_view_btn.setAutoRaise(False)
        self.grid_view_btn.setObjectName("grid_view_btn")
        self.view_mode_hlayout.addWidget(self.grid_view_btn)
        self.toolbar_hlayout.addLayout(self.view_mode_hlayout)
        self.search_widget = SearchWidget(self.toolbar_widget)
        self.search_widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.search_widget.setObjectName("search_widget")
        self.toolbar_hlayout.addWidget(self.search_widget)
        self.filter_btn = FilterMenuButton(self.toolbar_widget)
        self.filter_btn.setCheckable(True)
        self.filter_btn.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.filter_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.filter_btn.setObjectName("filter_btn")
        self.toolbar_hlayout.addWidget(self.filter_btn)
        self.details_button = QtGui.QToolButton(self.toolbar_widget)
        self.details_button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.details_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/tk-multi-breakdown2/icons/info-inactive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/tk-multi-breakdown2/icons/info-active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.details_button.setIcon(icon3)
        self.details_button.setCheckable(True)
        self.details_button.setChecked(False)
        self.details_button.setAutoRaise(False)
        self.details_button.setObjectName("details_button")
        self.toolbar_hlayout.addWidget(self.details_button)
        self.header_layout.addLayout(self.toolbar_hlayout)
        self.verticalLayout.addWidget(self.toolbar_widget)
        self.main_container = QtGui.QWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_container.sizePolicy().hasHeightForWidth())
        self.main_container.setSizePolicy(sizePolicy)
        self.main_container.setObjectName("main_container")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.main_container)
        self.verticalLayout_5.setSpacing(-1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.details_splitter = QtGui.QSplitter(self.main_container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_splitter.sizePolicy().hasHeightForWidth())
        self.details_splitter.setSizePolicy(sizePolicy)
        self.details_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.details_splitter.setObjectName("details_splitter")
        self.file_view_frame = QtGui.QFrame(self.details_splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_view_frame.sizePolicy().hasHeightForWidth())
        self.file_view_frame.setSizePolicy(sizePolicy)
        self.file_view_frame.setObjectName("file_view_frame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.file_view_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.file_view = GroupedItemView(self.file_view_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_view.sizePolicy().hasHeightForWidth())
        self.file_view.setSizePolicy(sizePolicy)
        self.file_view.setObjectName("file_view")
        self.verticalLayout_3.addWidget(self.file_view)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.details_panel = QtGui.QGroupBox(self.details_splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_panel.sizePolicy().hasHeightForWidth())
        self.details_panel.setSizePolicy(sizePolicy)
        self.details_panel.setMinimumSize(QtCore.QSize(300, 0))
        self.details_panel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.details_panel.setTitle("")
        self.details_panel.setObjectName("details_panel")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.details_panel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.file_details = ShotgunFolderWidget(self.details_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_details.sizePolicy().hasHeightForWidth())
        self.file_details.setSizePolicy(sizePolicy)
        self.file_details.setMinimumSize(QtCore.QSize(250, 0))
        self.file_details.setObjectName("file_details")
        self.verticalLayout_2.addWidget(self.file_details)
        self.file_history_view = QtGui.QListView(self.details_panel)
        self.file_history_view.setObjectName("file_history_view")
        self.verticalLayout_2.addWidget(self.file_history_view)
        self.verticalLayout_5.addWidget(self.details_splitter)
        self.footer_widget = QtGui.QWidget(self.main_container)
        self.footer_widget.setObjectName("footer_widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.footer_widget)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.size_slider = QtGui.QSlider(self.footer_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.size_slider.sizePolicy().hasHeightForWidth())
        self.size_slider.setSizePolicy(sizePolicy)
        self.size_slider.setMinimumSize(QtCore.QSize(150, 0))
        self.size_slider.setStyleSheet(" QSlider::handle:horizontal {\n"
"    border: 1px solid palette(base);\n"
"     border-radius: 3px;\n"
"     width: 4px;\n"
"     background: palette(light);\n"
" }")
        self.size_slider.setMinimum(20)
        self.size_slider.setMaximum(300)
        self.size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.size_slider.setObjectName("size_slider")
        self.horizontalLayout_2.addWidget(self.size_slider)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.select_all_outdated_button = QtGui.QPushButton(self.footer_widget)
        self.select_all_outdated_button.setMinimumSize(QtCore.QSize(125, 0))
        self.select_all_outdated_button.setObjectName("select_all_outdated_button")
        self.horizontalLayout_2.addWidget(self.select_all_outdated_button)
        self.update_selected_button = QtGui.QPushButton(self.footer_widget)
        self.update_selected_button.setMinimumSize(QtCore.QSize(125, 0))
        self.update_selected_button.setObjectName("update_selected_button")
        self.horizontalLayout_2.addWidget(self.update_selected_button)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.footer_widget)
        self.verticalLayout.addWidget(self.main_container)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.group_by_label.setText(QtGui.QApplication.translate("Dialog", "Group By:", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_btn.setText(QtGui.QApplication.translate("Dialog", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.select_all_outdated_button.setText(QtGui.QApplication.translate("Dialog", "Select all Outdated", None, QtGui.QApplication.UnicodeUTF8))
        self.update_selected_button.setText(QtGui.QApplication.translate("Dialog", "Update Selected", None, QtGui.QApplication.UnicodeUTF8))

from ..framework_qtwidgets import ShotgunFolderWidget, FilterMenuButton, SearchWidget, GroupedItemView
from . import resources_rc
